=== eikyusho/extensions/schema.xsd
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <!-- * TYPES   -->
    <xs:simpleType name="novel-list-idType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="trending"/>
            <xs:enumeration value="most-popular"/>
            <xs:enumeration value="recently-updated"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="novel-item-attrType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="attribute" type="xs:string"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="novelType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="text"/>
            <xs:enumeration value="selector"/>
        </xs:restriction>
    </xs:simpleType>


    <!-- * ELEMENTS  -->
    <xs:element name="novel-list">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="novel-item"/>
            </xs:sequence>
            <xs:attribute type="novel-list-idType" name="id" use="required"/>
            <xs:attribute type="xs:string" name="url" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="novel-item">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title" type="novel-item-attrType"/>
                <xs:element name="cover" type="novel-item-attrType"/>
                <xs:element name="link" type="novel-item-attrType"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="selector" use="required"/>
        </xs:complexType>
    </xs:element>

    <xs:element name="novel-meta">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="author" type="xs:string"/>
                <xs:element name="status" type="xs:string"/>
                <xs:element name="genre" type="xs:string"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="novel-status-map">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="ongoing" type="xs:string"/>
                <xs:element name="completed" type="xs:string"/>
                <xs:element name="hiatus" type="xs:string" minOccurs="0"/>
                <xs:element name="dropped" type="xs:string" minOccurs="0"/>
                <xs:element name="cancelled" type="xs:string" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- * ROOT ELEMENT -->
    <xs:element name="eks-source">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="metadata"/>
                <xs:element ref="discover"/>
                <xs:element ref="novel"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- * METADATA ELEMENT -->
    <xs:element name="metadata">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="name" type="xs:string"/>
                <xs:element name="base-url" type="xs:string"/>
                <xs:element name="version" type="xs:string"/>
                <xs:element name="language" type="lang"/>
                <xs:element ref="novel-status-map"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <!-- * DISCOVER ELEMENT -->
    <xs:element name="discover">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="novel-list" maxOccurs="unbounded" minOccurs="0"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="UniqueNovelListId">
            <xs:selector xpath="novel-list"/>
            <xs:field xpath="@id"/>
        </xs:unique>
    </xs:element>

    <!-- * NOVEL ELEMENT -->
    <xs:element name="novel">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="title" type="novel-item-attrType"/>
                <xs:element name="cover" type="novel-item-attrType"/>
                <xs:element name="author" type="novel-item-attrType"/>
                <xs:element name="chapter-count" type="novel-item-attrType"/>
                <xs:element name="views" type="novel-item-attrType"/>
                <xs:element name="status" type="novel-item-attrType"/>
                <xs:element name="genres" type="novel-item-attrType"/>
                <xs:element name="description" type="novel-item-attrType"/>
            </xs:sequence>
            <xs:attribute type="novelType" name="type" use="required"/>
        </xs:complexType>
    </xs:element>


    <!-- * LANG REFERENCE -->
    <xs:simpleType name="lang">
        <xs:restriction base="xs:string">
            <xs:enumeration value="en"/>
            <xs:enumeration value="pt"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== eikyusho/extensions/src/en/lightnovelworld/source.xml
<?xml version="1.0" encoding="UTF-8" ?>
<eks-source xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"  xsi:noNamespaceSchemaLocation="../extensions/schema.xsd">
    <metadata>
        <name>Light Novel World</name>
        <base-url>https://www.lightnovelworld.co</base-url>
        <version>1.0.0</version>
        <language>en</language>
    </metadata>

    <discover>
        <novel-list id="trending" url="/home">
            <novel-item selector="#index > section:nth-child(4) .section-body > ul > li">
                <title>.novel-title</title>
                <cover attribute="data-src">a > figure > img</cover>
                <link attribute="href">a</link>
            </novel-item>
        </novel-list>
        <novel-list id="most-popular" url="/ranking-04061612">
            <novel-item selector="#ranking > div.container > div > ul > li">
                <title>.title</title>
                <cover attribute="data-src">img</cover>
                <link attribute="href">a</link>
            </novel-item>
        </novel-list>
        <novel-list id="recently-updated" url="/latest-updates-04061612">
            <novel-item selector="#latest-updates > div > ul > .novel-item">
                <title>.novel-title</title>
                <cover attribute="data-src">img</cover>
                <link attribute="href">a</link>
            </novel-item>
        </novel-list>
    </discover>
</eks-source>

=== eikyusho/extensions/src/en/readnovelfull/source.xml
<?xml version="1.0" encoding="UTF-8" ?>
<eks-source xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="../../../schema.xsd">
    <metadata>
        <name>ReadNovelFull</name>
        <base-url>https://readnovelfull.com</base-url>
        <version>1.1.0</version>
        <language>en</language>
        <novel-status-map>
            <ongoing>onGoing</ongoing>
            <completed>Completed</completed>
        </novel-status-map>
    </metadata>

    <discover>
        <novel-list id="trending" url="/">
            Array.from(document.querySelectorAll('#index-novel-hot > div.index-novel > div.item'), item =>
            {
            return {
            title: item.querySelector('.title h3').textContent.trim(),
            cover: item.querySelector('img').src,
            link: item.querySelector('a').href
            };
            });
        </novel-list>
        <novel-list id="most-popular" url="/novel-list/most-popular-novel">
            Array.from(document.querySelectorAll('#list-page > .col-novel-main.archive .row'), item =>
            {
            return {
            title: item.querySelector('.novel-title').textContent.trim(),
            cover: item.querySelector('.cover').src,
            link: item.querySelector('a').href
            };
            });
        </novel-list>
        <novel-list id="recently-updated" url="/novel-list/latest-release-novel">
            Array.from(document.querySelectorAll('#list-page > .col-novel-main.archive .row'), item => {

            return {
            title: item.querySelector('.novel-title').textContent.trim(),
            cover: item.querySelector('.cover').src,
            link: item.querySelector('a').href,
            };
            });
        </novel-list>
    </discover>
</eks-source>
